### ISSUE TITLE
Haircut to the government interest rate

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#435]
We should parameterize the wedge between the interest rate on government debt and the market interest rate that represents the marginal product of capital.  This represents a reduced form risk premium in a model with no risk.  The model already allows the `r_gov` to differ from `r`, but we need to build in a parametrized wedge between the two.

We may want this to be flexible and allow for both a scaling and shift parameter.  e.g., `r_gov = m_gov * r - b_gov`, where `m_gov` is the scale parameter and `b_gov` is the shift parameter (though we should think about more appropriate names for these parameters).

cc @rickecon

**Comment by kerkphil** [comment]
Let the wedge depend on the amount of government debt outstanding as a percent of GDP?

r_gov = m_gov * r * (govt_debt / GDP) - b_gov

0 < m_gov < 1, b_gov > 0

**Comment by jdebacker** [comment]
@kerkphil I like that idea.  Any suggestions on how that could be calibrated?  

Relatedly, note that the gov't interest rate would still move with the market interest rate - which *is* affected by the amount of gov't debt (outside of the small open economy case).

**Comment by kerkphil** [comment]
Ed Gamber here at CBO has a paper in progress that shows an increase of 2 basis points per 1 percentage point increase in the Debt-to-GDP ratio.

Earlier work shows slightly larger effects at around 3 basis points

New Evidence on the Interest Rate Effects of Budget Deficits and Debt
Author(s): Thomas Laubach
Source: Journal of the European Economic Association, Vol. 7, No. 4 (Jun., 2009), pp. 858-
885
Published by: Oxford University Press
Stable URL: http://www.jstor.org/stable/40282791

**Comment by jdebacker** [comment]
In PR #437, @rickecon said:

> @jdebacker. We could put a little Cobb-Douglas preference aggregator into the household budget constraint where the savings amount b_{s+1,t+1} used to be. Let the choice of how much debt be d_{s+1,t+1}, let the interest rate on private capital be r_t, and let the haircut interest rate on government debt (savings) be r_{g,t}. Then the household budget constraint is (I dropped the j subscripts in everything but the market clearing conditions):

> hhbc
> 
> This results in an adjusted private capital savings Euler equation:
> 
> eulb
> 
> and a demand for government debt that is a fraction of private capital savings.
> 
> dst
> 
> Then the capital market clearing equation becomes two capital market clearing equations,
> 
> mc
> 
> and the government debt law of motion and closure rules change to have r_{g,t} in them. This leaves us still with just one really endogenous interest rate r_t, and then a government interest rate r_{g,t} that is a fairly trivial function of the private interest rate and a government debt amount that is a function of alpha_d, the two interest rates r_t and r_{g,t} and the savings amount b_{s+1,t+1}.

and

> @jdebacker. Also, in thinking about the form of the relationship between r_t and r_{g,t}, I think we will 

> need an indicator function in the following way. Let tau_d be the percent that r_{g,t} is lower than r_t. Let mu_d be the fixed number of basis points that r_{g,t} is less than r_t. And let I_{r>0} be an indicator function that is 1 if r_t>0 and is 0 otherwise.
> 
> haircut
> 
> This form of government borrowing rate haircut sets r_{g,t}=r_t in any cases in which the private rate r_t<=0.

I agree - the "portfolio preference aggregator" approach is a good one.  I think we do that.  Perhaps a more general CES form, though?

Regarding the indicator function --- isn't it really the negativity of the `r_{g,t}` that matters?  I.e., I'd think you'd want a function like (using your notation):

`r_{g,t} = max(0.001, tau_d * r - mu_d`

Am I missing something?  There are already bounds to keep `r_{t}` > 0 in the model (e.g., the firms' FOC for the choice of capital).

**Comment by rickecon** [comment]
@jdebacker . OK, I agree that it is the best to set up a perfectly competitive mutual fund industry that takes savings from households and lends it to firms and government. And we can easily set the production function as CES, and just calibrate it to be Cobb-Douglas initially.

**Comment by rickecon** [comment]
@jdebacker @kerkphil . QUESTION: If we assume this mutual fund industry that has a CES production technology, what happens when the government runs a surplus and is saving? This matters not only in the closed economy, but also in the open economy. Is the government getting the market return on its saving `r_t`, or is it getting the government borrowing rate `r_{g,t}`, or is it getting the composite mutual fund rate `r_{b,t}`? I know that the Fed (since 2008) has assets that are earning a market return.

If we want to make this distinction between the return on govt debt and the return on govt surpluses, I think it makes sense to have surpluses earn the market return, which would set `r_{g,t}=r_t=r_{b,t}` in that case. Let me know what you think.

**Comment by jdebacker** [comment]
I think this is reasonable.  In thinking about implementation, that market clearing condition changing in the case of `D_t <0` is certainly workable.  Having the household portfolio problem be condition on gov't debt seems a bit trickier.  Since our solution algorithm is to take r as given, solve the hh problem, and then use that solution to get the path for debt.  So at the stage of solving the household problem, we wouldn't know if the portfolio problem should or should not represent one without gov't debt.

Also, I suggest some different notation than `\tau_d` for the scale parameter.  Too easy to confuse with taxes.  Maybe a \beta_d? or \gamma_d or \rho_d??

**Comment by rickecon** [comment]
@jdebacker .

1) All of the switching around `D_t<0` is automatic and exogenous. It is taken care of with definitions. I am TeXing that up right now for your review. All the solution methods that require simply guessing the market interest rate `r_t` still hold, and the household problem doesn't change.

2) I think we should use `tau_d` as the variable for the slope wedge because it looks and acts and implies something very similar to a tax. In general, I like the notational convention of shares being `alpha`'s, CES share parameters being `gamma`'s, and tax rates or other rates being `tau`'s.

**Comment by jdebacker** [comment]
This issue was resolved with PR #449
