### ISSUE TITLE
Update OS license?

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#518]
@jdebacker. I think we should update the open source license for OG-USA. Here are some examples:
* EconARK's HARK model uses the [Apache License 2.0](https://github.com/econ-ark/HARK/blob/master/LICENSE)
* QuantEcon's lecture packages uses the [BSD 3-Clause "New" or "Revised" License](https://github.com/QuantEcon/QuantEconLectureAllPackages/blob/master/LICENSE)
* A software package, called economiccomplexity, that I am reviewing for the Journal of Open Source Software uses the [GNU General Public License v.3.0](https://github.com/pachamaltese/economiccomplexity/blob/master/LICENSE)

I think I like the [BSD 3-Clause "New" or "Revised" License](https://github.com/QuantEcon/QuantEconLectureAllPackages/blob/master/LICENSE) that QuantEcon uses. [This page](https://www.kiuwan.com/blog/comparison-popular-open-source-licenses/) has a nice orientation of the differences among the most popular licenses. Let me know what you think.

**Comment by jdebacker** [comment]
@rickecon I'm no expert on this and I the orientation didn't really give me sense that one is clearly superiors (I guess this is also evidences by the 3 econ software packages you cite all using different licenses).  

@MattHJensen I think you've thought more about this.  Any comments?

**Comment by MattHJensen** [comment]
**First of all, I Am Not A Lawyer. Please take all of this with a grain of salt and double check anything I say before you use it to make a decision.** 

It really depends on your goals. 

For Tax-Calculator, our goals were to maximize use in any and all contexts, minimize any single institution or person's claim on the IP, and keep things as simple as possible. I also wanted to make it very clear to the community that I wasn't planning to litigate in any circumstances, even if someone felt like someone else was "abusing" the code. CC0 was a good option for us. 

If you think you might litigate if someone doesn't cite the code how you want them to or something else (or you want to be able to threaten litigation), then you might want to consider an alternative license. The BSD license that Rick pointed out seems like a nice permissive license that provides useful controls over citation and disclaimers that MIT and Apache lack. One of the benefits of Apache is that it lets you copyright to the "authors of the code" rather than to specified individuals or institutions. 

Another good reason to consider an alternative license is that CCO isn't actually considered "open source" by the Open Source Initiative, which is looked to as an authority on which licenses are open source and which aren't. (Their board was split and so they didn't come down one way or the other). 

I've been happy with CC0, but I completely understand a desire to adopt a different license, especially if you don't mind specifying copyright holders, you want the option to litigate, or you care about what OSI calls open source.

**Comment by rickecon** [comment]
@jdebacker @MattHJensen . I like the ultimate permissiveness of the CC0. However, my short experience in our interactions with NumFOCUS and in my interaction with the Journal of Open Source Software suggest that the open source community really cares about having one of the [OSI-approved licenses](https://opensource.org/licenses). My read between the lines is that it is valuable to be explicit about the rights rather than the CC0 approach of waiving most rights. The OSI-approved licenses are explicit about which rights are waived and which are not. And all of them require citation, which I see as a nonbinding positive. I think this is important as we get ready to put OG-USA in its full glory (transition path) on C/S and as we start using OG-USA with the Tax Policy Center. I am an advocate of adopting the BSD 3 license.

I don't think any of us needs to be an attorney or an expert. The BSD 3 license is very lenient. Our colleagues use it. And other of our respected colleagues use more restrictive licenses. So if we want an OSI-approved license, and we want to be lenient, I think the BSD 3 is a good choice. And if we don't like it in the future, we can change it.

**Comment by jdebacker** [comment]
Ok - thanks for all this background @rickecon  and @MattHJensen.  I think I'd be glad to go with the BSD 3 also.

**Comment by rickecon** [comment]
After discussing with @MattHJensen and @jdebacker, we have decided to continue with the CC0 license currently in place with OG-USA. This is the least restrictive, which has many benefits for allowing the broadest use of the model.
