### ISSUE TITLE
UBI may not be correctly modeled

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#572]
I tried a simple OG-USA model run on CS (https://compute.studio/PSLmodels/OG-USA/107), setting all UBI parameters to 12000, and exempting it from taxes. These were the only parameters I changed:
![image](https://user-images.githubusercontent.com/6076111/83161657-8fcc1080-a0bd-11ea-88c6-49ba3f23c29c.png)

The results were unexpected, especially debt reduction:
![image](https://user-images.githubusercontent.com/6076111/83161446-50052900-a0bd-11ea-859f-7193643dc91a.png)

Might the UBI only be going into Tax-Calculator for MTRs/ETRs rather than as a government transfer?

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for opening this issue, I have not done any runs with UBI parameters before, so this is very helpful to see.

First, let me point out that UBI is going through TC and therefore entering OG-USA through it's effects on ETRs/MTRs (though, in your example, MTRs should not be affected).

Second, yes, the results on D are surprising given the lower net tax revenues that should results from this program.  I'm also surprised by some of the other macro changes (esp C).  Let me try to simulate this run locally so I have more results to digest.

cc @rickecon

**Comment by hdoupe** [comment]
@MaxGhenis just fyi, your sim is private. Their private by default on c/s.

**Comment by MaxGhenis** [comment]
Thanks @hdoupe, changed to public.

**Comment by jdebacker** [comment]
@MaxGhenis, I see that OG-USA is not handling the UBI correctly.  This is for at least three reasons:
1. UBI is not considered net tax liability from TC, so we missing the effect of the UBI to the net tax liability out of TC (this is the numerator of the ETR calculation).  However, TC does include the UBI in the measure of expanded income (the denominator of the ETR calculation).  This would tend to push ETRs down after implementation of a UBI (though not in the accurate way, where we'd want both the numerator and denominator to move by the amount of the UBI).  See [here](https://github.com/PSLmodels/OG-USA/blob/49f003a74349dd9e0849b33549cb9dba3da8c8e3/ogusa/get_micro_data.py#L178) for the relevant code.
2.  When "cleaning" the data before tax function estimation, [OG-USA drops values with very low income](https://github.com/PSLmodels/OG-USA/blob/49f003a74349dd9e0849b33549cb9dba3da8c8e3/ogusa/txfunc.py#L601) (mostly to avoid outlier ETR/MTRs when income values are near zero).  Generally, this works ok, because expanded income is the same for each observation out of TC for both the baseline and reform, so it's the same values dropped in each simulation.  However, a UBI (especially of the size you propose) can significantly change the filing units dropped due to the lower income threshold.  This will then cause sample selection to, in part, drive differences in the estimation of the ETR functions for the baseline and reform (and thus differences in the ETR functions aren't purely a function of the change in UBI parameters directly).
3. [Outlier ETRs are dropped](https://github.com/PSLmodels/OG-USA/blob/49f003a74349dd9e0849b33549cb9dba3da8c8e3/ogusa/txfunc.py#L599).  We've set the threshold for outlier ETRs at [-15%](https://github.com/PSLmodels/OG-USA/blob/49f003a74349dd9e0849b33549cb9dba3da8c8e3/ogusa/txfunc.py#L30).  But with a UBI of the size proposed here, this probably lead to many observations being dropped.  It would be nice to have the threshold used to determine outliers to vary with the policy proposed, but that is really tricky.  The -15% seemed fine for current law (where it was mostly the EITC pushing a handful of filers below this), but it is not great for the ETRs resulting from large UBI benefits.  

I can open a PR to start fixing these issues.  But please, let me know:
* If anything above isn't clear.
* If you have suggestions for setting income and ETR thresholds when cleaning data.

**Comment by jdebacker** [comment]
To follow up, I propose the following:

1. Adjust the numerator in the ETR calculations in `get_micro_data.py` to include UBI benefits.
2. Drop the restriction that `expanded_income` is above some minimum values in `txfunc.py`, keeping the restrictions on `labinc` and `capinc`.  This will keep some income restrictions (which is helpful), but exclude income restrictions based on an income concept that includes policy parameters (and therefore whose values would differ under the baseline and reform policies).
3. Change the constant in `txfunc.py` for the minimum allowable ETR.

**Comment by MaxGhenis** [comment]
Thanks Jason, so will the ETR change correct the debt projections?

**Comment by jdebacker** [comment]
@MaxGhenis, making one change to OG-USA to include UBI in the ETR calculation in `get_micro_data.py`:

```
'etr': ((calc1.array('combined') - calc1.array('ubi')) /
                calc1.array('expanded_income'))
```

Seems to get consumption and gov't debt going in the expected directions:
![MacroAgg_PctChange](https://user-images.githubusercontent.com/10715924/83308404-c6487f00-a1d4-11ea-9152-bc43442b5135.png)
![DebtGDPratio](https://user-images.githubusercontent.com/10715924/83308408-c8124280-a1d4-11ea-8c97-c4b4d93a26a7.png)


Upon further thought, I don't think I should change the denominator in this calculation since `expanded income` in the model will include the UBI, it should be included in the calculation here as well.

I will test out some of the other proposed changes soon.

**Comment by jdebacker** [comment]
@MaxGhenis UBI should now be modeled through the effective tax rate functions in OG-USA.  These updates were made in PR #573.
