### ISSUE TITLE
Odd steady-state government expenditures result in UBI experiment on Compute Studio

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#605]
I tried two UBI experiments on OG-USA in CS:
1. https://compute.studio/PSLmodels/OG-USA/121 which is $500/month/adult and $300/month/child
2. https://compute.studio/PSLmodels/OG-USA/122 which is the same but also increases the capital share from 0.35 to 0.5

Economic aggregates look to be in the expected direction for (1):
![image](https://user-images.githubusercontent.com/6076111/88973483-02976a80-d26c-11ea-8574-01e57081f16d.png)

But in (2), the steady-state government expenditure differences are the opposite sign compared to the transition path:

![image](https://user-images.githubusercontent.com/6076111/88973004-505fa300-d26b-11ea-992d-df89f0016a2b.png)

Seems odd. cc @rickecon as we discussed this yesterday.

**Comment by hdoupe** [comment]
Just noticed a C/S error related to this sim. I'll post the results in a minute. Sorry about that.

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for pointing this out.  I'm receiving and error on C/S when I try to download the results (I want to see what G is in the baseline and reform) -- maybe @hdoupe can help me identify the issue with that.

But it looks like the issue you are seeing is likely a result of the `gamma` parameter not being held constant between the baseline and reform runs.  [Line 78](https://github.com/PSLmodels/OG-USA/blob/bbee326e8c7007859a44e35d7b3aef93ffba401d/cs-config/cs_config/functions.py#L78) of `functions.py` filters parameters that should remain constant between the baseline and reform runs.  There is a typo there for the `gamma` and `epsilon` parameters, which read `gamma_s` and `epsilon_s`.  I'll open a PR to fix this and hopefully that solves the issue.

**Comment by hdoupe** [comment]
https://compute.studio/PSLmodels/OG-USA/122/

[d3593070-83dc-4b8e-910e-2312e1b812a9_renderable.zip](https://github.com/PSLmodels/OG-USA/files/5003775/d3593070-83dc-4b8e-910e-2312e1b812a9_renderable.zip)

**Comment by hdoupe** [comment]
https://compute.studio/PSLmodels/OG-USA/122/

[d3593070-83dc-4b8e-910e-2312e1b812a9_downloadable.zip](https://github.com/PSLmodels/OG-USA/files/5003786/d3593070-83dc-4b8e-910e-2312e1b812a9_downloadable.zip)

**Comment by hdoupe** [comment]
https://compute.studio/PSLmodels/OG-USA/121/

[347ddfd8-dacc-4820-ba86-431e5615e81e_downloadable.zip](https://github.com/PSLmodels/OG-USA/files/5003792/347ddfd8-dacc-4820-ba86-431e5615e81e_downloadable.zip)

**Comment by hdoupe** [comment]
[Fix](https://github.com/compute-tooling/compute-studio/commit/6e342be215b21118bf28e6e38b8c6a7c0180d5ad) is up. Sorry about that!

**Comment by jdebacker** [comment]
@hdoupe is amazing and got my "fix" up quick.  BUT, that wasn't it.  I did remove some unused parameters, but the `gamma` parameter *is* fixed (see [here](https://github.com/PSLmodels/OG-USA/blob/1fbdd0cff4124bee3033cf0f9076c92daf636559/cs-config/cs_config/functions.py#L173)).

The issue you are running into is that it is hard to interpret percentage changes in G when you cross zero.  The baseline in (1) results in positive G in the SS.  The baseline in (2) results in negative G in the SS.  Both (1) and (2) have G highly negative in the SS.  So the percentage changes you see are computed with a crossing of zero in case (1).  E.g., in (1) we have: G_baseline = 0.00188766, G_reform=-0.0989779.  Percentage change = (-0.0989779 - 0.00188766)/ 0.00188766 = -53.43 (-5343%) and in (2) we have: G_baseline = -0.039526 , G_reform=-0.2109212.  Percentage change = (-0.2109212 - -0.039526)/ -0.039526 = 4.33 (433%). 

Note that tax revenue is negative in the reform in (2) in all years after 2025.  Because of this it takes massive negative amount of government spending to stabilize the budget.  OG-USA will solve with unrealistic policies like this, but sometimes the output is hard to understand (and shouldn't really be used to evaluate policy) because we are pulling resources out of thin air when necessary by allowing G to go negative indefinitely.

**Comment by MaxGhenis** [comment]
Interesting, thanks for looking into it @jdebacker! And thanks @hdoupe for the quick fix.
