### ISSUE TITLE
Consider modeling the ETR/MTR deltas from a baseline, rather than baseline and reform separately

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#628]
Currently, the tax functions are modeled independently for each policy, including baseline and reform. This fits each policy best, but might not be maximizing the fit for the *delta* between baseline and reform. I think this could be part of what's causing the irregularities in the UBI experiment.

An alternative could be:
1. Fit the baseline as normal
2. Calculate the baseline-reform delta ETR/MTR for each tax unit in the microdata
3. Fit a new function to the deltas (with a different functional form, since this need not be increasing with income)
4. Add the baseline to the delta

In the UBI example, this would probably avoid the swings we saw, since UBI is strictly decreasing as an ETR delta with income.

**Comment by jdebacker** [comment]
@MaxGhenis -- I'm going to close this issue.  Some aspects of this approach are appealing, but it is not clear to me how one can bound these deltas in a way that ensures that the resulting tax functions yield non-decreasing marginal tax rates in income (something that is necessary to avoid non-convex budget sets and non-unique solutions).

Feel free to reopen of you want to discuss proposed solutions to that issue.  Otherwise, we can use Issue #574 to discuss how to improve the fit of tax functions.
