### ISSUE TITLE
Question about r in the outer loop

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#679]
@jdebacker. In the steady-state OG-USA computation, we guess an interest rate `rguess` in the outer loop which is the marginal product of capital. We use that interest rate for the initial guess for `BQ` in the steady-state in [line 598 of `SS.py`](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/SS.py#L598) because we don't have `r_hh` at that point. And we use `r_hh` in computing new values of `BQ` in [line 207 of `SS.py`](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/SS.py#L207).

Am I right that the law of motion for bequests in [equation (35) of the documentation](https://pslmodels.github.io/OG-USA/content/theory/market_clearing.html#total-bequests-law-of-motion) should be in terms of `r_hh`?

**Comment by jdebacker** [comment]
@rickecon observes:

> In the steady-state OG-USA computation, we guess an interest rate rguess in the outer loop which is the marginal product of capital. We use that interest rate for the initial guess for BQ in the steady-state in line 598 of SS.py because we don't have r_hh at that point. And we use r_hh in computing new values of BQ in line 207 of SS.py.

That's right.  We use `r` just for the initial guess - since we are already guessing `r` for the outer loop (and don't have all the info get determine `r_hh`) and it's probably not too far from `r_hh`, this gives us a decent initial guess at `BQ`.  But when solving for the eq'm, we use the correct `r_hh`.


He then asks:

> Am I right that the law of motion for bequests in equation (35) of the documentation should be in terms of r_hh?

Yes.  In fact, about every household equation in the documentation needs to be updated to note `r_hh`.  The docs get a little tricky to organize with all of these different cases, but I suppose we should write them as general as possible.

**Comment by rickecon** [comment]
@jdebacker. I am making these changes in the documentation in my `ubi` branch. I will make a PR as soon as the code is close enough to outline what I think is correct. I just made a PR to your `open_economy.md` PR to add in the changes that I had already made to that documentation in my `ubi` branch.
